### ISSUE TITLE
cannot run project due to  Error: Surprising path: /app/entry-points/server/index.js

### ISSUE THREAD

**Issue by ziadrida** [timothyarmes/ta-meteor-apollo-starter-kit#6]
The fix is to change package.json to add a . before the /app/ for both client and server
  "meteor": {
    "mainModule": {
      "client": "./app/entry-points/client/startup.js",
      "server": "./app/entry-points/server/index.js"
    }
  },

**Comment by timothyarmes** [comment]
Hmm, it's strange that I've never had any issues. I'll push a fix in any case though since it also works for me without thee slash.
